### PR TITLE
NFT tracking dev branch

### PR DESCRIPTION
**Pull request by kig**
This branch implements NFT tracking & background processing using a web worker. The NFT binding requires libjpeg-6b and runs very slowly for some reason.

### CODE REVIEW

**Comment by jeromeetienne** [comment]
im very interested in having worker support! i think it should be good especially on mobile :) 

i tried your branch but i got issues running an example ```examples/nft_worker_threejs.html``` require a ```js/artoolkit.proxy.js``` which isnt in the repo.

where can i find this file ? thanks :)

**Comment by kig** [comment]
Oops, forgot to include the proxy file! I pushed it just now

On 5 June 2016 at 14:28, Jerome Etienne <notifications@github.com> wrote:

> im very interested in having worker support! i think it should be good
> especially on mobile :)
>
> i tried your branch but i got issues running an example
> examples/nft_worker_threejs.html require a js/artoolkit.proxy.js which
> isnt in the repo.
>
> where can i find this file ? thanks :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/artoolkit/jsartoolkit5/pull/22#issuecomment-223813085>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAANtB3Bj7FIeSvcoUfs0Qon-z6TI6LRks5qIs7vgaJpZM4If5Gp>
> .
>



-- 
Ilmari Heikkinen

Web http://fhtr.net | Mail ilmari@fhtr.net | Skype ilmarihe | Twitter
@ilmarihei
Tel (UK) +447427139588

FHTR Ltd

Creative dev in London, working with agencies & artists to build campaign
websites, installations and innovative prototypes.

Company Number. 8157370
Registered in England

**Comment by yuccai** [comment]
Hi Kig,

I really like what you did and I would like a fluid NFT. I want to understand why your version is running slowly but I can't figure out how to build correctly artoolkit.min.js. I still have memory issues (Warning: Enlarging memory arrays, this is not fast!). I would like to know which version of emscripten you used.

**Comment by jeromeetienne** [comment]
im trying this pull-request, and got some exceptions with the nft+workers.

line 44 of .worker.js we need to serialize argument or the browser complain about serialization issue. see screenshot.js
```
ev.data.arguments.push(function() {
	var args = Array.prototype.slice.call(arguments);
	postMessage({method: ev.data.method, result: args, id: ev.data.id, callID: ev.data.callID});
});
```

screen shot 2017-01-30 at 22 04 19

**Comment by jeromeetienne** [comment]
im super close to merge this pull-request. 

Anybody against it ? speak now :)

**Comment by jeromeetienne** [comment]
i cloned this pr in jsartoolkit5/#nft to work on small details before merging it. Thanks again!

**Pull request merged**
