### PR TITLE
Feature/code cleanup

### PR DESCRIPTION
**Pull request by jensarps**
This is a quick code cleanup after a first static analysis.

There's still a lot to do in regards of working JSDoc blocks, but this is a start at least :)

The `master` and `dev` branches are, uh, kinda out of sync, so I decided to do the work on top of master.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
+1 Will you squash this later?

**Comment by philip-lamb** [comment]
Nice work. 'master' is definitely the correct branch. The 'dev' branch is just for historical interest and might be removed at some point.

**Comment by jensarps** [comment]
Great :) 

I _highly, strongly_ advise against squashing the commits into one huge `did some code cleanup` commit. But, well, I'm not the project owner, so I can only advise, not make decisions :)

**Comment by ralphtheninja** [comment]
> I highly, strongly advise against squashing the commits into one huge did some code cleanup commit. But, well, I'm not the project owner, so I can only advise, not make decisions :)

I don't like that idea either. Maybe group things together more, like "mark arg as optional" could be one commit etc.

**Comment by jensarps** [comment]
Ok, sounds reasonable. I'll see what my git-fu allows me to do ;)

**Comment by ralphtheninja** [comment]
`git reset --mixed ..` ;)

**Comment by jensarps** [comment]
OMG. I… I'm so sorry. 

I tried doing this with interactive rebase, as I'm more comfortable with that and… I totally screwed up. Hard. So hard I can't even figure out how to do undo this unholy mess.

So I created a new branch, reset it and re-comitted the changes in groups.

Can we please just forget this PR, pretend it never happened and look over at #20 instead?

**Comment by jeromeetienne** [comment]
as you said, this one is a duplicate from #20, so im closing this one. reopen if you feel it is necessary

**Pull request closed without merging**
