### PR TITLE
Enhanced build description ... 

### PR DESCRIPTION
**Pull request by ThorstenBux**
... and enabled to be able to use ARToolKit5_ROOT env variable for build script.

### CODE REVIEW

**Comment by philip-lamb** [comment]
👍

**Comment by ralphtheninja** [comment]
No PR discussions welcome, or?

**Comment by philip-lamb** [comment]
Sorry, your comments came in between when I loaded the page and when I merged. @ThorstenBux please take Lars-Magnus' comments into account and make a follow-up commit.

**Comment by ralphtheninja** [comment]
> Sorry, your comments came in between when I loaded the page and when I merged. @ThorstenBux please take Lars-Magnus' comments into account and make a follow-up commit.

Np. Just wondering :)

**Comment by ThorstenBux** [comment]
Right on

**Pull request merged**
